[package]
name = "torus-backend"
version = "0.1.0"
authors = ["Broch Stilley <brochington@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json_payload_derive = { path = "./proc_macros/json_payload_derive" }
actix-rt = "1.0.0"
actix-web = "2.0.0"
actix-web-codegen = "0.2.0"
actix-cors = "0.2.0"
actix-service = "1.0.2"
diesel = { version = "1.4.3", features = ["postgres", "r2d2", "chrono", "uuidv07", "serde_json"] }
dotenv = "0.14.1"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
listenfd = "0.3.3"
futures = "0.3.1"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
jsonwebtoken = "6.0.1"
reqwest = "0.9.20"
url = "2.1.0"
percent-encoding = "2.1.0"
chrono = { version = "0.4.9", features = ["serde"] }
serde_qs = "0.5"
log = "0.4.8"
env_logger = "0.7.1"
rusoto_core = "0.43.0"
rusoto_ses = { version = "0.43.0", features = ["serialize_structs"] }
time = "~0.2.14"

[features]
default = []
local_dev = []
