CREATE TABLE files (
  id UUID PRIMARY KEY NOT NULL, -- Not generated by the db.
  project_id UUID NOT NULL,
  name TEXT NOT NULL, -- original file name, without extension
  key UUID NOT NULL, -- unique file key, used to identify file in storage (S3, GCS, etc) across versions
  extension TEXT NOT NULL, -- file extension, e.g. "jpg"
  version INT NOT NULL, -- version number, incremented on each new row insertion for file version upload.
  size INT NOT NULL, -- file size in bytes
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by UUID NOT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,
  deleted_by UUID DEFAULT NULL
);

SELECT sqlx_manage_updated_at('files');